import crypto from 'node:crypto';

/**
 * Generates a cryptographically random nonce for CSP.
 * Uses 16 bytes (128 bits) encoded as base64, producing a 24-character string.
 */
export function generateNonce(): string {
  return crypto.randomBytes(16).toString('base64');
}

/**
 * Builds the full set of HTTP security headers for a request.
 *
 * @param nonce - The per-request nonce generated by `generateNonce()`
 * @param isProd - Whether the app is running in production (enforce CSP + HSTS)
 * @param r2Domain - Optional R2 endpoint domain for `connect-src`
 * @returns A map of header name → header value
 */
export function buildSecurityHeaders(
  nonce: string,
  isProd: boolean,
  r2Domain?: string,
): Record<string, string> {
  const connectSrc = r2Domain ? `connect-src 'self' ${r2Domain}` : "connect-src 'self'";

  const cspDirectives = [
    "default-src 'self'",
    `script-src 'nonce-${nonce}' 'strict-dynamic'`,
    `style-src 'nonce-${nonce}'`,
    "img-src 'self' data: https:",
    connectSrc,
    "frame-src 'self'",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
    'upgrade-insecure-requests',
  ].join('; ');

  const cspHeaderName = isProd ? 'Content-Security-Policy' : 'Content-Security-Policy-Report-Only';

  const headers: Record<string, string> = {
    [cspHeaderName]: cspDirectives,
    'X-Frame-Options': 'DENY',
    'X-Content-Type-Options': 'nosniff',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'geolocation=(), microphone=(), camera=()',
  };

  if (isProd) {
    headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains';
  }

  return headers;
}
