import crypto from 'node:crypto';

/**
 * Generates a cryptographically random nonce for CSP.
 * Uses 16 bytes (128 bits) encoded as base64, producing a 24-character string.
 */
export function generateNonce(): string {
  return crypto.randomBytes(16).toString('base64');
}

/**
 * Builds the full set of HTTP security headers for a request.
 *
 * @param nonce - The per-request nonce generated by `generateNonce()`
 * @param isProd - Whether the app is running in production (enforce CSP + HSTS)
 * @param r2Domain - Optional R2 endpoint domain; the endpoint and its bucket subdomains are allowed
 *   for network requests and PDF object previews
 * @returns A map of header name → header value
 */
export function buildSecurityHeaders(
  nonce: string,
  isProd: boolean,
  r2Domain?: string,
): Record<string, string> {
  const r2Sources = r2Domain ? `https://${r2Domain} https://*.${r2Domain}` : '';
  const connectSrc = `connect-src 'self'${r2Sources ? ` ${r2Sources}` : ''}`;
  const objectSrc = r2Sources ? `object-src ${r2Sources}` : "object-src 'none'";

  const cspDirectives = [
    "default-src 'self'",
    `script-src 'nonce-${nonce}' 'strict-dynamic'`,
    `style-src 'nonce-${nonce}' 'sha256-CIxDM5jnsGiKqXs2v7NKCY5MzdR9gu6TtiMJrDw29AY='`,
    "style-src-attr 'unsafe-inline'",
    "img-src 'self' data: https:",
    connectSrc,
    "frame-src 'self'",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    objectSrc,
    // upgrade-insecure-requests only in enforced CSP (prod).
    // In Report-Only mode (dev), it has no effect and Chrome logs a console error.
    ...(isProd ? ['upgrade-insecure-requests'] : []),
  ].join('; ');

  const cspHeaderName = isProd ? 'Content-Security-Policy' : 'Content-Security-Policy-Report-Only';

  const headers: Record<string, string> = {
    [cspHeaderName]: cspDirectives,
    'X-Frame-Options': 'DENY',
    'X-Content-Type-Options': 'nosniff',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'geolocation=(), microphone=(), camera=()',
  };

  if (isProd) {
    headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains';
  }

  return headers;
}
