/** @vitest-environment node */
import { describe, it, expect } from 'vitest';
import { sql } from 'drizzle-orm';
import { getDb } from '@/db/index';

/**
 * Integration test: verifies that the migration generated by `pnpm db:generate`
 * and applied by `pnpm db:migrate` creates all 9 expected indexes in the actual
 * PostgreSQL database.
 *
 * This test queries the `pg_indexes` system view — no test data is inserted or
 * modified. It is opt-in (lives under `tests/integration/`) and excluded from
 * the default `pnpm test` suite and the pre-push coverage gate.
 *
 * Prerequisites:
 * - Docker container `simak-postgres` running on port 5432
 * - `pnpm db:migrate` has been run against the dev DB
 */
describe('migration-applied: indexes exist in database', () => {
  const db = getDb();

  /** Expected index names after the PERF-7..14 migration is applied. */
  const EXPECTED_INDEXES = [
    // PERF-7: assignmentStudents (was zero indexes)
    'assignment_students_assignment_id_student_id_idx',
    'assignment_students_student_id_idx',
    // PERF-8: notifications.createdAt (fixes admin dashboard full-table scan)
    'notifications_created_at_idx',
    // PERF-9: templateCheckpoints (was zero indexes)
    'template_checkpoints_template_id_order_idx',
    // PERF-10: users (was zero indexes)
    'users_role_deleted_at_idx',
    // PERF-11: consultations — REPLACES consultations_status_idx
    'consultations_assignment_id_status_idx',
    // PERF-12: extensionRequests
    'extension_requests_assignment_id_student_id_idx',
    // PERF-13: auditLog.actorId
    'audit_log_actor_id_idx',
    // PERF-14: reviews — REPLACES reviews_submission_id_idx
    'reviews_submission_id_created_at_idx',
  ];

  /** Indexes that should have been DROPPED by the migration (replaced by composites). */
  const DROPPED_INDEXES = [
    // PERF-11: replaced by consultations_assignment_id_status_idx
    'consultations_status_idx',
    // PERF-14: replaced by reviews_submission_id_created_at_idx
    'reviews_submission_id_idx',
  ];

  async function getIndexNames(): Promise<Set<string>> {
    const result = await db.execute(
      sql`SELECT indexname FROM pg_indexes WHERE schemaname = 'public'`,
    );
    return new Set(result.map((row) => row.indexname as string));
  }

  it('all 9 expected indexes exist in the database', async () => {
    const indexes = await getIndexNames();
    const missing = EXPECTED_INDEXES.filter((name) => !indexes.has(name));
    expect(missing).toEqual([]);
  });

  it('the 2 replaced indexes have been dropped from the database', async () => {
    const indexes = await getIndexNames();
    const stillPresent = DROPPED_INDEXES.filter((name) => indexes.has(name));
    expect(stillPresent).toEqual([]);
  });
});
