// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually

import type { Locales } from './types'

export function detectLocale(locale?: string): Locales {
  if (locale === 'id') return 'id'
  return 'en'
}
