// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually

export type Locales = 'en' | 'id';

export type Translation = {
  app: {
    name: string;
    tagline: string;
  };
  auth: {
    login: string;
    logout: string;
    email: string;
    password: string;
    signIn: string;
    signUp: string;
    forgotPassword: string;
    resetPassword: string;
    invalidCredentials: string;
    sessionExpired: string;
  };
  nav: {
    dashboard: string;
    assignments: string;
    consultations: string;
    settings: string;
    users: string;
    templates: string;
  };
  common: {
    save: string;
    cancel: string;
    delete: string;
    edit: string;
    create: string;
    search: string;
    filter: string;
    loading: string;
    error: string;
    success: string;
    confirm: string;
    back: string;
    next: string;
    submit: string;
    noResults: string;
    viewAll: string;
  };
  theme: {
    light: string;
    dark: string;
    toggle: string;
  };
  language: {
    en: string;
    id: string;
    switch: string;
  };
  error: {
    notFound: string;
    forbidden: string;
    serverError: string;
    required: string;
    invalidEmail: string;
  };
  adminSidebar: {
    dashboard: string;
    users: string;
    templates: string;
  };
  adminUsers: {
    title: string;
    newUser: string;
    table: {
      name: string;
      email: string;
      role: string;
      createdAt: string;
      actions: string;
    };
    empty: string;
    createPrompt: string;
    deleteConfirm: string;
    deleteSuccess: string;
    createSuccess: string;
    createSuccessNoEmail: string;
    updateSuccess: string;
    linkGenerated: string;
    linkCopied: string;
    generateLink: string;
    edit: string;
    role_admin: string;
    role_instructor: string;
    role_student: string;
    emailVerified: string;
    notVerified: string;
    createdAt: string;
  };
};

export type TranslationFunctions = Record<string, (key: string) => string>;

export type LocaleTranslation = {
  locale: Locales;
  translations: Translation;
};
