// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually

export type Locales = 'en' | 'id'

export type Translation = {
  app: {
    name: string
    tagline: string
  }
  auth: {
    login: string
    logout: string
    email: string
    password: string
    signIn: string
    signUp: string
    forgotPassword: string
    resetPassword: string
    invalidCredentials: string
    sessionExpired: string
    confirmPassword: string
    passwordMismatch: string
    linkExpired: string
    setupPassword: string
    setupSuccess: string
    resetSuccess: string
    checkYourEmail: string
    forgotPasswordSent: string
  }
  nav: {
    dashboard: string
    assignments: string
    reviews: string
    consultations: string
    settings: string
    users: string
    templates: string
    welcome: string
    role_student: string
    role_instructor: string
    role_admin: string
  }
  adminUsers: {
    title: string
    newUser: string
    table: {
      name: string
      email: string
      role: string
      createdAt: string
      actions: string
    }
    empty: string
    createPrompt: string
    deleteConfirm: string
    deleteSuccess: string
    createSuccess: string
    createSuccessNoEmail: string
    updateSuccess: string
    linkGenerated: string
    linkCopied: string
    generateLink: string
    edit: string
    role_superadmin: string
    allRoles: string
    searchPlaceholder: string
    role_admin: string
    role_instructor: string
    role_student: string
    emailVerified: string
    notVerified: string
    createdAt: string
  }
  adminTemplates: {
    title: string
    newTemplate: string
    searchPlaceholder: string
    filterByType: string
    checkpointCount: string
    empty: string
    createPrompt: string
    form: {
      name: string
      type: string
      checkpoints: string
      checkpointName: string
      addCheckpoint: string
      removeCheckpoint: string
      minConsultations: string
      moveUp: string
      moveDown: string
    }
    actions: {
      edit: string
      duplicate: string
      delete: string
    }
    createSuccess: string
    updateSuccess: string
    duplicateSuccess: string
    deleteConfirm: string
    deleteInUse: string
    deleteSuccess: string
    inUseBanner: string
  }
  common: {
    save: string
    cancel: string
    delete: string
    edit: string
    create: string
    search: string
    filter: string
    loading: string
    error: string
    success: string
    confirm: string
    back: string
    next: string
    previous: string
    submit: string
    refresh: string
    hide: string
    view: string
    noResults: string
    viewAll: string
    page: string
  }
  theme: {
    light: string
    dark: string
    toggle: string
  }
  language: {
    en: string
    id: string
    switch: string
  }
  error: {
    notFound: string
    forbidden: string
    serverError: string
    required: string
    invalidEmail: string
  }
  adminSidebar: {
    dashboard: string
    users: string
    templates: string
    auditLog: string
  }
  adminAuditLog: {
    title: string
    subtitle: string
    searchPlaceholder: string
    allActions: string
    dateFrom: string
    dateTo: string
    empty: string
    showing: string
    auditTable: {
      timestamp: string
      action: string
      actor: string
      entityType: string
      entityId: string
      details: string
    }
    actionLabels: {
      userCreated: string
      userDeleted: string
      templateCreated: string
      templateUpdated: string
      templateDeleted: string
      assignmentCreated: string
      reviewPassed: string
      reviewRevised: string
      checkpointUnlocked: string
      deadlineExtended: string
      consultationVerified: string
      consultationRejected: string
    }
  }
  studentSidebar: {
    dashboard: string
    assignments: string
  }
  studentDashboard: {
    title: string
    subtitle: string
    activeAssignments: string
    noActiveAssignments: string
    upcomingDeadlines: string
    noUpcomingDeadlines: string
    pendingReviews: string
    noPendingReviews: string
    consultationReminders: string
    noConsultationReminders: string
    overdue: string
    underReview: string
    pending: string
    submittedAgo: string
  }
  instructorDashboard: {
    title: string
    subtitle: string
    pendingReviews: string
    noPendingReviews: string
    recentSubmissions: string
    noRecentSubmissions: string
    assignmentOverview: string
    noAssignments: string
    quickActions: string
    goToReviewQueue: string
    reviewQueueDesc: string
    manageAssignments: string
    manageAssignmentsDesc: string
    pendingCount: string
  }
  adminDashboard: {
    title: string
    subtitle: string
    totalUsers: string
    instructors: string
    students: string
    activeAssignments: string
    pendingReviews: string
    activeConsultations: string
    recentActivity: string
    noRecentActivity: string
    escalationAlerts: string
    noEscalationAlerts: string
    quickActions: string
    manageUsers: string
    manageUsersDesc: string
    manageTemplates: string
    manageTemplatesDesc: string
    student: string
    daysOverdue: string
  }
  studentAssignments: {
    title: string
    subtitle: string
    searchPlaceholder: string
    finalDeadline: string
    progress: string
    empty: string
    emptyPrompt: string
    timeline: string
    submit: string
    resubmit: string
    viewSubmission: string
    consultations: string
    blockedByPrevious: string
    blockedByConsultations: string
    notFound: string
    notFoundDescription: string
    status: {
      passed: string
      under_review: string
      submitted: string
      locked: string
      unlocked: string
      revise: string
      overdue: string
    }
  }
  instructorReviews: {
    title: string
    subtitle: string
    allAssignments: string
    empty: string
    emptyPrompt: string
    slaNotReviewed: string
    slaOnTime: string
    slaApproaching: string
    slaBreached: string
    submittedFile: string
    versionLabel: string
    downloadPdf: string
    downloadFile: string
    reviewHistory: string
    passed: string
    revise: string
    decision: string
    pass: string
    comment: string
    commentPlaceholder: string
    feedbackFile: string
    uploadFeedback: string
    revisionDeadline: string
    submitReview: string
    submitting: string
    revisionDeadlineRequired: string
    submitError: string
    reviewSubmitted: string
    backToQueue: string
  }
  instructorAssignments: {
    title: string
    subtitle: string
    searchPlaceholder: string
    createNew: string
    myAssignments: string
    allAssignments: string
    assignedToMe: string
    myCheckpoints: string
    pendingReviews: string
    submission: string
    submissionCount: string
    averageGrade: string
    percentage: string
    noAssignments: string
    emptyPrompt: string
  }
  files: {
    title: string
    upload: string
    uploadSuccess: string
    uploadError: string
    fileSize: string
    file: string
    download: string
    downloadError: string
    empty: string
    emptyPrompt: string
  }
  consultations: {
    title: string
    student: string
    instructor: string
    edit: string
    cancel: string
    submit: string
    logs: string
    verify: string
    reject: string
    records: string
    empty: string
    emptyPrompt: string
    pending: string
    verified: string
    rejected: string
    comments: string
    commentPlaceholder: string
    submitError: string
    rejectError: string
  }
  notifications: {
    title: string
    markAllRead: string
    empty: string
    unreadCount: string
    groups: {
      newReviews: string
      consultations: string
      submissions: string
      system: string
    }
  }
}

export type TranslationFunctions = Record<string, (key: string) => string>

export type LocaleTranslation = {
  locale: Locales
  translations: Translation
}
