import { describe, it, expect, beforeAll } from 'vitest';
import { execSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const projectRoot = resolve(import.meta.dirname, '..', '..', '..');
const typesPath = resolve(projectRoot, 'src', 'i18n', 'types.ts');
const detectLocalePath = resolve(projectRoot, 'src', 'i18n', 'detect-locale.ts');
const enPath = resolve(projectRoot, 'locales', 'en.json');
const idPath = resolve(projectRoot, 'locales', 'id.json');

describe('i18n type generation', () => {
  beforeAll(() => {
    // Run the generator before tests
    execSync('pnpm generate:i18n', { cwd: projectRoot, stdio: 'pipe' });
  });

  it('should generate src/i18n/types.ts successfully', () => {
    expect(existsSync(typesPath)).toBe(true);
    const content = readFileSync(typesPath, 'utf-8');
    expect(content).toContain('Auto-generated by scripts/generate-i18n-types.ts');
    expect(content).toContain("export type Locales = 'en' | 'id'");
    expect(content).toContain('export type Translation = {');
  });

  it('should generate src/i18n/detect-locale.ts successfully', () => {
    expect(existsSync(detectLocalePath)).toBe(true);
    const content = readFileSync(detectLocalePath, 'utf-8');
    expect(content).toContain('Auto-generated by scripts/generate-i18n-types.ts');
    expect(content).toContain('export function detectLocale');
  });

  it('should have no duplicate sections in Translation type', () => {
    const content = readFileSync(typesPath, 'utf-8');
    // Read all section names from the Translation type by finding lines like "sectionName: {"
    const sectionPattern = /^  (\w+):\s*\{$/gm;
    const sections: string[] = [];
    let match;
    while ((match = sectionPattern.exec(content)) !== null) {
      sections.push(match[1]);
    }
    const uniqueSections = new Set(sections);
    expect(sections.length).toBe(uniqueSections.size);
  });

  it('should include all sections from en.json in the Translation type', () => {
    const en = JSON.parse(readFileSync(enPath, 'utf-8'));
    const typesContent = readFileSync(typesPath, 'utf-8');
    const expectedSections = Object.keys(en);

    for (const section of expectedSections) {
      expect(typesContent).toContain(`  ${section}: {`);
    }
  });

  it('should have no empty sections in the Translation type', () => {
    const content = readFileSync(typesPath, 'utf-8');
    // Each section must have at least one key
    const sections = content.match(/(\w+):\s*\{[^}]+}/g);
    expect(sections).not.toBeNull();
    for (const section of sections ?? []) {
      expect(section).toMatch(/:\s*string/);
    }
  });

  it('should have all en.json keys covered by id.json', () => {
    const en = JSON.parse(readFileSync(enPath, 'utf-8'));
    const id = JSON.parse(readFileSync(idPath, 'utf-8'));

    function getAllKeys(obj: Record<string, unknown>, prefix = ''): string[] {
      const keys: string[] = [];
      for (const [key, value] of Object.entries(obj)) {
        const fullKey = prefix ? `${prefix}.${key}` : key;
        if (typeof value === 'string') {
          keys.push(fullKey);
        } else if (typeof value === 'object' && value !== null) {
          keys.push(...getAllKeys(value as Record<string, unknown>, fullKey));
        }
      }
      return keys;
    }

    const enKeys = new Set(getAllKeys(en));
    const idKeys = new Set(getAllKeys(id));

    const missing = [...enKeys].filter((k) => !idKeys.has(k));
    expect(missing).toEqual([]);
  });
});
