// Placeholder for typesafe-i18n type generation
// This script will be replaced with full typesafe-i18n generator integration
// For now, it creates the minimal type stubs needed for compilation

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const typesDir = resolve(import.meta.dirname, '..', 'src', 'i18n');

const typesContent = `// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually

export type Locales = 'en' | 'id'

export type Translation = {
  app: {
    name: string
    tagline: string
  }
  auth: {
    login: string
    logout: string
    email: string
    password: string
    signIn: string
    signUp: string
    forgotPassword: string
    resetPassword: string
    invalidCredentials: string
    sessionExpired: string
  }
  nav: {
    dashboard: string
    assignments: string
    reviews: string
    consultations: string
    settings: string
    users: string
    templates: string
  }
  common: {
    save: string
    cancel: string
    delete: string
    edit: string
    create: string
    search: string
    filter: string
    loading: string
    error: string
    success: string
    confirm: string
    back: string
    next: string
    submit: string
    noResults: string
    viewAll: string
    page: string
  }
  theme: {
    light: string
    dark: string
    toggle: string
  }
  language: {
    en: string
    id: string
    switch: string
  }
  error: {
    notFound: string
    forbidden: string
    serverError: string
    required: string
    invalidEmail: string
  }
  adminSidebar: {
    dashboard: string
    users: string
    templates: string
  }
  studentSidebar: {
    dashboard: string
    assignments: string
  }
  studentDashboard: {
    title: string
    subtitle: string
    activeAssignments: string
    noActiveAssignments: string
    upcomingDeadlines: string
    noUpcomingDeadlines: string
    pendingReviews: string
    noPendingReviews: string
    consultationReminders: string
    noConsultationReminders: string
    overdue: string
    underReview: string
    pending: string
    submittedAgo: string
  }
  studentAssignments: {
    title: string
    subtitle: string
    searchPlaceholder: string
    finalDeadline: string
    progress: string
    empty: string
    emptyPrompt: string
    timeline: string
    submit: string
    consultations: string
    blockedByPrevious: string
    blockedByConsultations: string
    notFound: string
    notFoundDescription: string
    status: {
      passed: string
      under_review: string
      submitted: string
      locked: string
      unlocked: string
      revise: string
      overdue: string
    }
  }
  adminUsers: {
    title: string
    newUser: string
    table: {
      name: string
      email: string
      role: string
      createdAt: string
      actions: string
    }
    empty: string
    createPrompt: string
    deleteConfirm: string
    deleteSuccess: string
    createSuccess: string
    createSuccessNoEmail: string
    updateSuccess: string
    linkGenerated: string
    linkCopied: string
    generateLink: string
    edit: string
    role_admin: string
    role_instructor: string
    role_student: string
    emailVerified: string
    notVerified: string
    createdAt: string
  }
  instructorReviews: {
    title: string
    subtitle: string
    allAssignments: string
    empty: string
    emptyPrompt: string
    slaNotReviewed: string
    slaOnTime: string
    slaApproaching: string
    slaBreached: string
    submittedFile: string
    versionLabel: string
    downloadPdf: string
    downloadFile: string
    reviewHistory: string
    passed: string
    revise: string
    decision: string
    pass: string
    comment: string
    commentPlaceholder: string
    feedbackFile: string
    uploadFeedback: string
    revisionDeadline: string
    submitReview: string
    submitting: string
    revisionDeadlineRequired: string
    submitError: string
    reviewSubmitted: string
    backToQueue: string
  }
  adminTemplates: {
    title: string
    newTemplate: string
    searchPlaceholder: string
    filterByType: string
    checkpointCount: string
    empty: string
    createPrompt: string
    form: {
      name: string
      type: string
      checkpoints: string
      checkpointName: string
      addCheckpoint: string
      removeCheckpoint: string
      moveUp: string
      moveDown: string
    }
    actions: {
      edit: string
      duplicate: string
      delete: string
    }
    createSuccess: string
    updateSuccess: string
    duplicateSuccess: string
    deleteConfirm: string
    deleteInUse: string
    deleteSuccess: string
    inUseBanner: string
  }
  notifications: {
    title: string
    markAllRead: string
    empty: string
    unreadCount: string
    groups: {
      newReviews: string
      consultations: string
      submissions: string
      system: string
    }
  }
}

export type TranslationFunctions = Record<string, (key: string) => string>

export type LocaleTranslation = {
  locale: Locales
  translations: Translation
}
`;

if (!existsSync(typesDir)) {
  mkdirSync(typesDir, { recursive: true });
}

writeFileSync(resolve(typesDir, 'types.ts'), typesContent);

// Also create a detect-locale stub
const detectLocaleContent = `
// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually

import type { Locales } from './types'

export function detectLocale(locale?: string): Locales {
  if (locale === 'id') return 'id'
  return 'en'
}
`;

writeFileSync(resolve(typesDir, 'detect-locale.ts'), detectLocaleContent);

console.log('✅ i18n types generated successfully.');
