// Placeholder for typesafe-i18n type generation
// This script will be replaced with full typesafe-i18n generator integration
// For now, it creates the minimal type stubs needed for compilation

import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

const typesDir = resolve(import.meta.dirname, '..', 'src', 'i18n')

const typesContent = `// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually

export type Locales = 'en' | 'id'

export type Translation = {
  app: {
    name: string
    tagline: string
  }
  auth: {
    login: string
    logout: string
    email: string
    password: string
    signIn: string
    signUp: string
    forgotPassword: string
    resetPassword: string
    invalidCredentials: string
    sessionExpired: string
  }
  nav: {
    dashboard: string
    assignments: string
    consultations: string
    settings: string
    users: string
    templates: string
  }
  common: {
    save: string
    cancel: string
    delete: string
    edit: string
    create: string
    search: string
    filter: string
    loading: string
    error: string
    success: string
    confirm: string
    back: string
    next: string
    submit: string
    noResults: string
    viewAll: string
  }
  theme: {
    light: string
    dark: string
    toggle: string
  }
  language: {
    en: string
    id: string
    switch: string
  }
  error: {
    notFound: string
    forbidden: string
    serverError: string
    required: string
    invalidEmail: string
  }
}

export type TranslationFunctions = Record<string, (key: string) => string>

export type LocaleTranslation = {
  locale: Locales
  translations: Translation
}
`

if (!existsSync(typesDir)) {
  mkdirSync(typesDir, { recursive: true })
}

writeFileSync(resolve(typesDir, 'types.ts'), typesContent)

// Also create a detect-locale stub
const detectLocaleContent = `
// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually

import type { Locales } from './types'

export function detectLocale(locale?: string): Locales {
  if (locale === 'id') return 'id'
  return 'en'
}
`

writeFileSync(resolve(typesDir, 'detect-locale.ts'), detectLocaleContent)

console.log('✅ i18n types generated successfully.')
