import { writeFileSync, readFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const localeFile = resolve(import.meta.dirname, '..', 'locales', 'en.json');
const typesDir = resolve(import.meta.dirname, '..', 'src', 'i18n');

/** Indent a block of lines by `n` spaces */
function indent(block: string, n: number): string {
  const pad = ' '.repeat(n);
  return block
    .split('\n')
    .map((l) => (l.trim() ? pad + l : l))
    .join('\n');
}

/**
 * Recursively generate TypeScript type definition from a JSON object.
 * String values → `key: string`
 * Nested objects → `key: { ... }`
 */
function toTypeDef(obj: Record<string, unknown>, depth = 0): string {
  const entries: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'string') {
      entries.push(`${key}: string`);
    } else if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      const nested = toTypeDef(value as Record<string, unknown>, depth + 1);
      entries.push(`${key}: {\n${indent(nested, 2)}\n}`);
    }
    // Skip arrays and other types — shouldn't occur in locale JSON
  }

  return entries.join('\n');
}

// ---- Read en.json ----
let en: Record<string, unknown>;
try {
  en = JSON.parse(readFileSync(localeFile, 'utf-8'));
} catch (err) {
  console.error('❌ Failed to read en.json:', err instanceof Error ? err.message : String(err));
  process.exit(1);
}

// Generate Translation type
const translationBody = toTypeDef(en);
const typesContent = `// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually — derived from locales/en.json

export type Locales = 'en' | 'id'

export type Translation = {
${indent(translationBody, 2)}
}

export type TranslationFunctions = Record<string, (key: string) => string>

export type LocaleTranslation = {
  locale: Locales
  translations: Translation
}
`;

if (!existsSync(typesDir)) mkdirSync(typesDir, { recursive: true });
writeFileSync(resolve(typesDir, 'types.ts'), typesContent);

const detectLocaleContent = `
// Auto-generated by scripts/generate-i18n-types.ts — do not edit manually
import type { Locales } from './types'
export function detectLocale(locale?: string): Locales {
  if (locale === 'id') return 'id'
  return 'en'
}
`;

writeFileSync(resolve(typesDir, 'detect-locale.ts'), detectLocaleContent);
console.log('✅ i18n types generated successfully from locales/en.json');
