/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedInstructorRouteImport } from './routes/_authenticated/instructor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as UnauthenticatedAuthSetupPasswordRouteImport } from './routes/_unauthenticated/auth/setup-password'
import { Route as UnauthenticatedAuthResetPasswordRouteImport } from './routes/_unauthenticated/auth/reset-password'
import { Route as UnauthenticatedAuthLoginRouteImport } from './routes/_unauthenticated/auth/login'
import { Route as UnauthenticatedAuthForgotPasswordRouteImport } from './routes/_unauthenticated/auth/forgot-password'
import { Route as AuthenticatedStudentAssignmentsIndexRouteImport } from './routes/_authenticated/student/assignments/index'
import { Route as AuthenticatedInstructorAssignmentsIndexRouteImport } from './routes/_authenticated/instructor/assignments/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminTemplatesIndexRouteImport } from './routes/_authenticated/admin/templates/index'
import { Route as AuthenticatedStudentAssignmentsIdRouteImport } from './routes/_authenticated/student/assignments/$id'
import { Route as AuthenticatedInstructorAssignmentsNewRouteImport } from './routes/_authenticated/instructor/assignments/new'
import { Route as AuthenticatedInstructorAssignmentsIdRouteImport } from './routes/_authenticated/instructor/assignments/$id'
import { Route as AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRouteImport } from './routes/_authenticated/student/assignments/$id.checkpoints.$checkpointId'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstructorRoute = AuthenticatedInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedAuthSetupPasswordRoute =
  UnauthenticatedAuthSetupPasswordRouteImport.update({
    id: '/auth/setup-password',
    path: '/auth/setup-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthResetPasswordRoute =
  UnauthenticatedAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthLoginRoute =
  UnauthenticatedAuthLoginRouteImport.update({
    id: '/auth/login',
    path: '/auth/login',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthForgotPasswordRoute =
  UnauthenticatedAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedStudentAssignmentsIndexRoute =
  AuthenticatedStudentAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedInstructorAssignmentsIndexRoute =
  AuthenticatedInstructorAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesIndexRoute =
  AuthenticatedAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStudentAssignmentsIdRoute =
  AuthenticatedStudentAssignmentsIdRouteImport.update({
    id: '/assignments/$id',
    path: '/assignments/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedInstructorAssignmentsNewRoute =
  AuthenticatedInstructorAssignmentsNewRouteImport.update({
    id: '/assignments/new',
    path: '/assignments/new',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorAssignmentsIdRoute =
  AuthenticatedInstructorAssignmentsIdRouteImport.update({
    id: '/assignments/$id',
    path: '/assignments/$id',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute =
  AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRouteImport.update({
    id: '/checkpoints/$checkpointId',
    path: '/checkpoints/$checkpointId',
    getParentRoute: () => AuthenticatedStudentAssignmentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/reset-password': typeof UnauthenticatedAuthResetPasswordRoute
  '/auth/setup-password': typeof UnauthenticatedAuthSetupPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/instructor/assignments/$id': typeof AuthenticatedInstructorAssignmentsIdRoute
  '/instructor/assignments/new': typeof AuthenticatedInstructorAssignmentsNewRoute
  '/student/assignments/$id': typeof AuthenticatedStudentAssignmentsIdRouteWithChildren
  '/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/instructor/assignments/': typeof AuthenticatedInstructorAssignmentsIndexRoute
  '/student/assignments/': typeof AuthenticatedStudentAssignmentsIndexRoute
  '/student/assignments/$id/checkpoints/$checkpointId': typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/reset-password': typeof UnauthenticatedAuthResetPasswordRoute
  '/auth/setup-password': typeof UnauthenticatedAuthSetupPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/instructor/assignments/$id': typeof AuthenticatedInstructorAssignmentsIdRoute
  '/instructor/assignments/new': typeof AuthenticatedInstructorAssignmentsNewRoute
  '/student/assignments/$id': typeof AuthenticatedStudentAssignmentsIdRouteWithChildren
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/instructor/assignments': typeof AuthenticatedInstructorAssignmentsIndexRoute
  '/student/assignments': typeof AuthenticatedStudentAssignmentsIndexRoute
  '/student/assignments/$id/checkpoints/$checkpointId': typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_unauthenticated/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/_unauthenticated/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/_unauthenticated/auth/reset-password': typeof UnauthenticatedAuthResetPasswordRoute
  '/_unauthenticated/auth/setup-password': typeof UnauthenticatedAuthSetupPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/instructor/assignments/$id': typeof AuthenticatedInstructorAssignmentsIdRoute
  '/_authenticated/instructor/assignments/new': typeof AuthenticatedInstructorAssignmentsNewRoute
  '/_authenticated/student/assignments/$id': typeof AuthenticatedStudentAssignmentsIdRouteWithChildren
  '/_authenticated/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/instructor/assignments/': typeof AuthenticatedInstructorAssignmentsIndexRoute
  '/_authenticated/student/assignments/': typeof AuthenticatedStudentAssignmentsIndexRoute
  '/_authenticated/student/assignments/$id/checkpoints/$checkpointId': typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/instructor'
    | '/student'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/api/auth/$'
    | '/instructor/assignments/$id'
    | '/instructor/assignments/new'
    | '/student/assignments/$id'
    | '/admin/templates/'
    | '/admin/users/'
    | '/instructor/assignments/'
    | '/student/assignments/'
    | '/student/assignments/$id/checkpoints/$checkpointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/instructor'
    | '/student'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/api/auth/$'
    | '/instructor/assignments/$id'
    | '/instructor/assignments/new'
    | '/student/assignments/$id'
    | '/admin/templates'
    | '/admin/users'
    | '/instructor/assignments'
    | '/student/assignments'
    | '/student/assignments/$id/checkpoints/$checkpointId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/instructor'
    | '/_authenticated/student'
    | '/_unauthenticated/auth/forgot-password'
    | '/_unauthenticated/auth/login'
    | '/_unauthenticated/auth/reset-password'
    | '/_unauthenticated/auth/setup-password'
    | '/api/auth/$'
    | '/_authenticated/instructor/assignments/$id'
    | '/_authenticated/instructor/assignments/new'
    | '/_authenticated/student/assignments/$id'
    | '/_authenticated/admin/templates/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/instructor/assignments/'
    | '/_authenticated/student/assignments/'
    | '/_authenticated/student/assignments/$id/checkpoints/$checkpointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor': {
      id: '/_authenticated/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthenticatedInstructorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/auth/setup-password': {
      id: '/_unauthenticated/auth/setup-password'
      path: '/auth/setup-password'
      fullPath: '/auth/setup-password'
      preLoaderRoute: typeof UnauthenticatedAuthSetupPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/reset-password': {
      id: '/_unauthenticated/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof UnauthenticatedAuthResetPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/login': {
      id: '/_unauthenticated/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof UnauthenticatedAuthLoginRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/forgot-password': {
      id: '/_unauthenticated/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof UnauthenticatedAuthForgotPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/student/assignments/': {
      id: '/_authenticated/student/assignments/'
      path: '/assignments'
      fullPath: '/student/assignments/'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/instructor/assignments/': {
      id: '/_authenticated/instructor/assignments/'
      path: '/assignments'
      fullPath: '/instructor/assignments/'
      preLoaderRoute: typeof AuthenticatedInstructorAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates/': {
      id: '/_authenticated/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/assignments/$id': {
      id: '/_authenticated/student/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/student/assignments/$id'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/instructor/assignments/new': {
      id: '/_authenticated/instructor/assignments/new'
      path: '/assignments/new'
      fullPath: '/instructor/assignments/new'
      preLoaderRoute: typeof AuthenticatedInstructorAssignmentsNewRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/assignments/$id': {
      id: '/_authenticated/instructor/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/instructor/assignments/$id'
      preLoaderRoute: typeof AuthenticatedInstructorAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/student/assignments/$id/checkpoints/$checkpointId': {
      id: '/_authenticated/student/assignments/$id/checkpoints/$checkpointId'
      path: '/checkpoints/$checkpointId'
      fullPath: '/student/assignments/$id/checkpoints/$checkpointId'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRouteImport
      parentRoute: typeof AuthenticatedStudentAssignmentsIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminTemplatesIndexRoute: typeof AuthenticatedAdminTemplatesIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminTemplatesIndexRoute: AuthenticatedAdminTemplatesIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedInstructorRouteChildren {
  AuthenticatedInstructorAssignmentsIdRoute: typeof AuthenticatedInstructorAssignmentsIdRoute
  AuthenticatedInstructorAssignmentsNewRoute: typeof AuthenticatedInstructorAssignmentsNewRoute
  AuthenticatedInstructorAssignmentsIndexRoute: typeof AuthenticatedInstructorAssignmentsIndexRoute
}

const AuthenticatedInstructorRouteChildren: AuthenticatedInstructorRouteChildren =
  {
    AuthenticatedInstructorAssignmentsIdRoute:
      AuthenticatedInstructorAssignmentsIdRoute,
    AuthenticatedInstructorAssignmentsNewRoute:
      AuthenticatedInstructorAssignmentsNewRoute,
    AuthenticatedInstructorAssignmentsIndexRoute:
      AuthenticatedInstructorAssignmentsIndexRoute,
  }

const AuthenticatedInstructorRouteWithChildren =
  AuthenticatedInstructorRoute._addFileChildren(
    AuthenticatedInstructorRouteChildren,
  )

interface AuthenticatedStudentAssignmentsIdRouteChildren {
  AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute: typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute
}

const AuthenticatedStudentAssignmentsIdRouteChildren: AuthenticatedStudentAssignmentsIdRouteChildren =
  {
    AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute:
      AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute,
  }

const AuthenticatedStudentAssignmentsIdRouteWithChildren =
  AuthenticatedStudentAssignmentsIdRoute._addFileChildren(
    AuthenticatedStudentAssignmentsIdRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentAssignmentsIdRoute: typeof AuthenticatedStudentAssignmentsIdRouteWithChildren
  AuthenticatedStudentAssignmentsIndexRoute: typeof AuthenticatedStudentAssignmentsIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentAssignmentsIdRoute:
    AuthenticatedStudentAssignmentsIdRouteWithChildren,
  AuthenticatedStudentAssignmentsIndexRoute:
    AuthenticatedStudentAssignmentsIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInstructorRoute: typeof AuthenticatedInstructorRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInstructorRoute: AuthenticatedInstructorRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedAuthForgotPasswordRoute: typeof UnauthenticatedAuthForgotPasswordRoute
  UnauthenticatedAuthLoginRoute: typeof UnauthenticatedAuthLoginRoute
  UnauthenticatedAuthResetPasswordRoute: typeof UnauthenticatedAuthResetPasswordRoute
  UnauthenticatedAuthSetupPasswordRoute: typeof UnauthenticatedAuthSetupPasswordRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedAuthForgotPasswordRoute:
    UnauthenticatedAuthForgotPasswordRoute,
  UnauthenticatedAuthLoginRoute: UnauthenticatedAuthLoginRoute,
  UnauthenticatedAuthResetPasswordRoute: UnauthenticatedAuthResetPasswordRoute,
  UnauthenticatedAuthSetupPasswordRoute: UnauthenticatedAuthSetupPasswordRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
