/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student';
import { Route as AuthenticatedInstructorRouteImport } from './routes/_authenticated/instructor';
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin';
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$';
import { Route as UnauthenticatedAuthVerifyBackupCodeRouteImport } from './routes/_unauthenticated/auth/verify-backup-code';
import { Route as UnauthenticatedAuthVerify2faRouteImport } from './routes/_unauthenticated/auth/verify-2fa';
import { Route as UnauthenticatedAuthSetupPasswordRouteImport } from './routes/_unauthenticated/auth/setup-password';
import { Route as UnauthenticatedAuthResetPasswordRouteImport } from './routes/_unauthenticated/auth/reset-password';
import { Route as UnauthenticatedAuthLoginRouteImport } from './routes/_unauthenticated/auth/login';
import { Route as UnauthenticatedAuthForgotPasswordRouteImport } from './routes/_unauthenticated/auth/forgot-password';
import { Route as AuthenticatedStudentSettingsRouteImport } from './routes/_authenticated/student/settings';
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard';
import { Route as AuthenticatedInstructorSettingsRouteImport } from './routes/_authenticated/instructor/settings';
import { Route as AuthenticatedInstructorDashboardRouteImport } from './routes/_authenticated/instructor/dashboard';
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings';
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard';
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log';
import { Route as AuthenticatedStudentAssignmentsIndexRouteImport } from './routes/_authenticated/student/assignments/index';
import { Route as AuthenticatedInstructorReviewsIndexRouteImport } from './routes/_authenticated/instructor/reviews/index';
import { Route as AuthenticatedInstructorAssignmentsIndexRouteImport } from './routes/_authenticated/instructor/assignments/index';
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index';
import { Route as AuthenticatedAdminTemplatesIndexRouteImport } from './routes/_authenticated/admin/templates/index';
import { Route as AuthenticatedStudentAssignmentsIdRouteImport } from './routes/_authenticated/student/assignments/$id';
import { Route as AuthenticatedInstructorReviewsSubmissionIdRouteImport } from './routes/_authenticated/instructor/reviews/$submissionId';
import { Route as AuthenticatedInstructorAssignmentsNewRouteImport } from './routes/_authenticated/instructor/assignments/new';
import { Route as AuthenticatedInstructorAssignmentsIdRouteImport } from './routes/_authenticated/instructor/assignments/$id';
import { Route as AuthenticatedAdminTemplatesTemplateIdRouteImport } from './routes/_authenticated/admin/templates/$templateId';
import { Route as AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRouteImport } from './routes/_authenticated/student/assignments/$id.checkpoints.$checkpointId';
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
    id: '/_unauthenticated',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedRoute = AuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedInstructorRoute = AuthenticatedInstructorRouteImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedRoute,
});
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
    id: '/api/auth/$',
    path: '/api/auth/$',
    getParentRoute: () => rootRouteImport,
});
const UnauthenticatedAuthVerifyBackupCodeRoute = UnauthenticatedAuthVerifyBackupCodeRouteImport.update({
    id: '/auth/verify-backup-code',
    path: '/auth/verify-backup-code',
    getParentRoute: () => UnauthenticatedRoute,
});
const UnauthenticatedAuthVerify2faRoute = UnauthenticatedAuthVerify2faRouteImport.update({
    id: '/auth/verify-2fa',
    path: '/auth/verify-2fa',
    getParentRoute: () => UnauthenticatedRoute,
});
const UnauthenticatedAuthSetupPasswordRoute = UnauthenticatedAuthSetupPasswordRouteImport.update({
    id: '/auth/setup-password',
    path: '/auth/setup-password',
    getParentRoute: () => UnauthenticatedRoute,
});
const UnauthenticatedAuthResetPasswordRoute = UnauthenticatedAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => UnauthenticatedRoute,
});
const UnauthenticatedAuthLoginRoute = UnauthenticatedAuthLoginRouteImport.update({
    id: '/auth/login',
    path: '/auth/login',
    getParentRoute: () => UnauthenticatedRoute,
});
const UnauthenticatedAuthForgotPasswordRoute = UnauthenticatedAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => UnauthenticatedRoute,
});
const AuthenticatedStudentSettingsRoute = AuthenticatedStudentSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStudentRoute,
});
const AuthenticatedStudentDashboardRoute = AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRoute,
});
const AuthenticatedInstructorSettingsRoute = AuthenticatedInstructorSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedInstructorRoute,
});
const AuthenticatedInstructorDashboardRoute = AuthenticatedInstructorDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedInstructorRoute,
});
const AuthenticatedAdminSettingsRoute = AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
});
const AuthenticatedAdminDashboardRoute = AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
});
const AuthenticatedAdminAuditLogRoute = AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRoute,
});
const AuthenticatedStudentAssignmentsIndexRoute = AuthenticatedStudentAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => AuthenticatedStudentRoute,
});
const AuthenticatedInstructorReviewsIndexRoute = AuthenticatedInstructorReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedInstructorRoute,
});
const AuthenticatedInstructorAssignmentsIndexRoute = AuthenticatedInstructorAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => AuthenticatedInstructorRoute,
});
const AuthenticatedAdminUsersIndexRoute = AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
});
const AuthenticatedAdminTemplatesIndexRoute = AuthenticatedAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedAdminRoute,
});
const AuthenticatedStudentAssignmentsIdRoute = AuthenticatedStudentAssignmentsIdRouteImport.update({
    id: '/assignments/$id',
    path: '/assignments/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
});
const AuthenticatedInstructorReviewsSubmissionIdRoute = AuthenticatedInstructorReviewsSubmissionIdRouteImport.update({
    id: '/reviews/$submissionId',
    path: '/reviews/$submissionId',
    getParentRoute: () => AuthenticatedInstructorRoute,
});
const AuthenticatedInstructorAssignmentsNewRoute = AuthenticatedInstructorAssignmentsNewRouteImport.update({
    id: '/assignments/new',
    path: '/assignments/new',
    getParentRoute: () => AuthenticatedInstructorRoute,
});
const AuthenticatedInstructorAssignmentsIdRoute = AuthenticatedInstructorAssignmentsIdRouteImport.update({
    id: '/assignments/$id',
    path: '/assignments/$id',
    getParentRoute: () => AuthenticatedInstructorRoute,
});
const AuthenticatedAdminTemplatesTemplateIdRoute = AuthenticatedAdminTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedAdminRoute,
});
const AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute = AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRouteImport.update({
    id: '/checkpoints/$checkpointId',
    path: '/checkpoints/$checkpointId',
    getParentRoute: () => AuthenticatedStudentAssignmentsIdRoute,
});
const AuthenticatedAdminRouteChildren = {
    AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTemplatesTemplateIdRoute: AuthenticatedAdminTemplatesTemplateIdRoute,
    AuthenticatedAdminTemplatesIndexRoute: AuthenticatedAdminTemplatesIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
};
const AuthenticatedAdminRouteWithChildren = AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren);
const AuthenticatedInstructorRouteChildren = {
    AuthenticatedInstructorDashboardRoute: AuthenticatedInstructorDashboardRoute,
    AuthenticatedInstructorSettingsRoute: AuthenticatedInstructorSettingsRoute,
    AuthenticatedInstructorAssignmentsIdRoute: AuthenticatedInstructorAssignmentsIdRoute,
    AuthenticatedInstructorAssignmentsNewRoute: AuthenticatedInstructorAssignmentsNewRoute,
    AuthenticatedInstructorReviewsSubmissionIdRoute: AuthenticatedInstructorReviewsSubmissionIdRoute,
    AuthenticatedInstructorAssignmentsIndexRoute: AuthenticatedInstructorAssignmentsIndexRoute,
    AuthenticatedInstructorReviewsIndexRoute: AuthenticatedInstructorReviewsIndexRoute,
};
const AuthenticatedInstructorRouteWithChildren = AuthenticatedInstructorRoute._addFileChildren(AuthenticatedInstructorRouteChildren);
const AuthenticatedStudentAssignmentsIdRouteChildren = {
    AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute: AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute,
};
const AuthenticatedStudentAssignmentsIdRouteWithChildren = AuthenticatedStudentAssignmentsIdRoute._addFileChildren(AuthenticatedStudentAssignmentsIdRouteChildren);
const AuthenticatedStudentRouteChildren = {
    AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
    AuthenticatedStudentSettingsRoute: AuthenticatedStudentSettingsRoute,
    AuthenticatedStudentAssignmentsIdRoute: AuthenticatedStudentAssignmentsIdRouteWithChildren,
    AuthenticatedStudentAssignmentsIndexRoute: AuthenticatedStudentAssignmentsIndexRoute,
};
const AuthenticatedStudentRouteWithChildren = AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren);
const AuthenticatedRouteChildren = {
    AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
    AuthenticatedInstructorRoute: AuthenticatedInstructorRouteWithChildren,
    AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
};
const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren);
const UnauthenticatedRouteChildren = {
    UnauthenticatedAuthForgotPasswordRoute: UnauthenticatedAuthForgotPasswordRoute,
    UnauthenticatedAuthLoginRoute: UnauthenticatedAuthLoginRoute,
    UnauthenticatedAuthResetPasswordRoute: UnauthenticatedAuthResetPasswordRoute,
    UnauthenticatedAuthSetupPasswordRoute: UnauthenticatedAuthSetupPasswordRoute,
    UnauthenticatedAuthVerify2faRoute: UnauthenticatedAuthVerify2faRoute,
    UnauthenticatedAuthVerifyBackupCodeRoute: UnauthenticatedAuthVerifyBackupCodeRoute,
};
const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(UnauthenticatedRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AuthenticatedRoute: AuthenticatedRouteWithChildren,
    UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
    ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
