/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedInstructorRouteImport } from './routes/_authenticated/instructor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiCalendarIcsRouteImport } from './routes/api/calendar.ics'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as UnauthenticatedAuthVerifyBackupCodeRouteImport } from './routes/_unauthenticated/auth/verify-backup-code'
import { Route as UnauthenticatedAuthVerify2faRouteImport } from './routes/_unauthenticated/auth/verify-2fa'
import { Route as UnauthenticatedAuthSetupPasswordRouteImport } from './routes/_unauthenticated/auth/setup-password'
import { Route as UnauthenticatedAuthResetPasswordRouteImport } from './routes/_unauthenticated/auth/reset-password'
import { Route as UnauthenticatedAuthLoginRouteImport } from './routes/_unauthenticated/auth/login'
import { Route as UnauthenticatedAuthForgotPasswordRouteImport } from './routes/_unauthenticated/auth/forgot-password'
import { Route as AuthenticatedStudentSettingsRouteImport } from './routes/_authenticated/student/settings'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard'
import { Route as AuthenticatedStudentAcademicRecordsRouteImport } from './routes/_authenticated/student/academic-records'
import { Route as AuthenticatedInstructorSettingsRouteImport } from './routes/_authenticated/instructor/settings'
import { Route as AuthenticatedInstructorFeedbackSnippetsRouteImport } from './routes/_authenticated/instructor/feedback-snippets'
import { Route as AuthenticatedInstructorDashboardRouteImport } from './routes/_authenticated/instructor/dashboard'
import { Route as AuthenticatedInstructorAnalyticsRouteImport } from './routes/_authenticated/instructor/analytics'
import { Route as AuthenticatedInstructorAcademicRecordsRouteImport } from './routes/_authenticated/instructor/academic-records'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminEmailQueueRouteImport } from './routes/_authenticated/admin/email-queue'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAcademicRecordsRouteImport } from './routes/_authenticated/admin/academic-records'
import { Route as AuthenticatedAdminAcademicContextRouteImport } from './routes/_authenticated/admin/academic-context'
import { Route as AuthenticatedStudentAssignmentsIndexRouteImport } from './routes/_authenticated/student/assignments/index'
import { Route as AuthenticatedInstructorReviewsIndexRouteImport } from './routes/_authenticated/instructor/reviews/index'
import { Route as AuthenticatedInstructorInterventionsIndexRouteImport } from './routes/_authenticated/instructor/interventions/index'
import { Route as AuthenticatedInstructorAssignmentsIndexRouteImport } from './routes/_authenticated/instructor/assignments/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminTemplatesIndexRouteImport } from './routes/_authenticated/admin/templates/index'
import { Route as AuthenticatedStudentAssignmentsIdRouteImport } from './routes/_authenticated/student/assignments/$id'
import { Route as AuthenticatedInstructorReviewsSubmissionIdRouteImport } from './routes/_authenticated/instructor/reviews/$submissionId'
import { Route as AuthenticatedInstructorAssignmentsNewRouteImport } from './routes/_authenticated/instructor/assignments/new'
import { Route as AuthenticatedInstructorAssignmentsIdRouteImport } from './routes/_authenticated/instructor/assignments/$id'
import { Route as AuthenticatedAdminUsersImportRouteImport } from './routes/_authenticated/admin/users/import'
import { Route as AuthenticatedAdminTemplatesImportRouteImport } from './routes/_authenticated/admin/templates/import'
import { Route as AuthenticatedAdminTemplatesTemplateIdRouteImport } from './routes/_authenticated/admin/templates/$templateId'
import { Route as AuthenticatedInstructorAssignmentsIdGradebookRouteImport } from './routes/_authenticated/instructor/assignments/$id.gradebook'
import { Route as AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRouteImport } from './routes/_authenticated/student/assignments/$id.checkpoints.$checkpointId'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstructorRoute = AuthenticatedInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiCalendarIcsRoute = ApiCalendarIcsRouteImport.update({
  id: '/api/calendar/ics',
  path: '/api/calendar/ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedAuthVerifyBackupCodeRoute =
  UnauthenticatedAuthVerifyBackupCodeRouteImport.update({
    id: '/auth/verify-backup-code',
    path: '/auth/verify-backup-code',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthVerify2faRoute =
  UnauthenticatedAuthVerify2faRouteImport.update({
    id: '/auth/verify-2fa',
    path: '/auth/verify-2fa',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthSetupPasswordRoute =
  UnauthenticatedAuthSetupPasswordRouteImport.update({
    id: '/auth/setup-password',
    path: '/auth/setup-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthResetPasswordRoute =
  UnauthenticatedAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthLoginRoute =
  UnauthenticatedAuthLoginRouteImport.update({
    id: '/auth/login',
    path: '/auth/login',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthForgotPasswordRoute =
  UnauthenticatedAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedStudentSettingsRoute =
  AuthenticatedStudentSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentAcademicRecordsRoute =
  AuthenticatedStudentAcademicRecordsRouteImport.update({
    id: '/academic-records',
    path: '/academic-records',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedInstructorSettingsRoute =
  AuthenticatedInstructorSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorFeedbackSnippetsRoute =
  AuthenticatedInstructorFeedbackSnippetsRouteImport.update({
    id: '/feedback-snippets',
    path: '/feedback-snippets',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorDashboardRoute =
  AuthenticatedInstructorDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorAnalyticsRoute =
  AuthenticatedInstructorAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorAcademicRecordsRoute =
  AuthenticatedInstructorAcademicRecordsRouteImport.update({
    id: '/academic-records',
    path: '/academic-records',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailQueueRoute =
  AuthenticatedAdminEmailQueueRouteImport.update({
    id: '/email-queue',
    path: '/email-queue',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAcademicRecordsRoute =
  AuthenticatedAdminAcademicRecordsRouteImport.update({
    id: '/academic-records',
    path: '/academic-records',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAcademicContextRoute =
  AuthenticatedAdminAcademicContextRouteImport.update({
    id: '/academic-context',
    path: '/academic-context',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStudentAssignmentsIndexRoute =
  AuthenticatedStudentAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedInstructorReviewsIndexRoute =
  AuthenticatedInstructorReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorInterventionsIndexRoute =
  AuthenticatedInstructorInterventionsIndexRouteImport.update({
    id: '/interventions/',
    path: '/interventions/',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorAssignmentsIndexRoute =
  AuthenticatedInstructorAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesIndexRoute =
  AuthenticatedAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedStudentAssignmentsIdRoute =
  AuthenticatedStudentAssignmentsIdRouteImport.update({
    id: '/assignments/$id',
    path: '/assignments/$id',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedInstructorReviewsSubmissionIdRoute =
  AuthenticatedInstructorReviewsSubmissionIdRouteImport.update({
    id: '/reviews/$submissionId',
    path: '/reviews/$submissionId',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorAssignmentsNewRoute =
  AuthenticatedInstructorAssignmentsNewRouteImport.update({
    id: '/assignments/new',
    path: '/assignments/new',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorAssignmentsIdRoute =
  AuthenticatedInstructorAssignmentsIdRouteImport.update({
    id: '/assignments/$id',
    path: '/assignments/$id',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedAdminUsersImportRoute =
  AuthenticatedAdminUsersImportRouteImport.update({
    id: '/users/import',
    path: '/users/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesImportRoute =
  AuthenticatedAdminTemplatesImportRouteImport.update({
    id: '/templates/import',
    path: '/templates/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesTemplateIdRoute =
  AuthenticatedAdminTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedInstructorAssignmentsIdGradebookRoute =
  AuthenticatedInstructorAssignmentsIdGradebookRouteImport.update({
    id: '/gradebook',
    path: '/gradebook',
    getParentRoute: () => AuthenticatedInstructorAssignmentsIdRoute,
  } as any)
const AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute =
  AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRouteImport.update({
    id: '/checkpoints/$checkpointId',
    path: '/checkpoints/$checkpointId',
    getParentRoute: () => AuthenticatedStudentAssignmentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/admin/academic-context': typeof AuthenticatedAdminAcademicContextRoute
  '/admin/academic-records': typeof AuthenticatedAdminAcademicRecordsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/email-queue': typeof AuthenticatedAdminEmailQueueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/instructor/academic-records': typeof AuthenticatedInstructorAcademicRecordsRoute
  '/instructor/analytics': typeof AuthenticatedInstructorAnalyticsRoute
  '/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/instructor/feedback-snippets': typeof AuthenticatedInstructorFeedbackSnippetsRoute
  '/instructor/settings': typeof AuthenticatedInstructorSettingsRoute
  '/student/academic-records': typeof AuthenticatedStudentAcademicRecordsRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/settings': typeof AuthenticatedStudentSettingsRoute
  '/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/reset-password': typeof UnauthenticatedAuthResetPasswordRoute
  '/auth/setup-password': typeof UnauthenticatedAuthSetupPasswordRoute
  '/auth/verify-2fa': typeof UnauthenticatedAuthVerify2faRoute
  '/auth/verify-backup-code': typeof UnauthenticatedAuthVerifyBackupCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/calendar/ics': typeof ApiCalendarIcsRoute
  '/admin/templates/$templateId': typeof AuthenticatedAdminTemplatesTemplateIdRoute
  '/admin/templates/import': typeof AuthenticatedAdminTemplatesImportRoute
  '/admin/users/import': typeof AuthenticatedAdminUsersImportRoute
  '/instructor/assignments/$id': typeof AuthenticatedInstructorAssignmentsIdRouteWithChildren
  '/instructor/assignments/new': typeof AuthenticatedInstructorAssignmentsNewRoute
  '/instructor/reviews/$submissionId': typeof AuthenticatedInstructorReviewsSubmissionIdRoute
  '/student/assignments/$id': typeof AuthenticatedStudentAssignmentsIdRouteWithChildren
  '/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/instructor/assignments/': typeof AuthenticatedInstructorAssignmentsIndexRoute
  '/instructor/interventions/': typeof AuthenticatedInstructorInterventionsIndexRoute
  '/instructor/reviews/': typeof AuthenticatedInstructorReviewsIndexRoute
  '/student/assignments/': typeof AuthenticatedStudentAssignmentsIndexRoute
  '/instructor/assignments/$id/gradebook': typeof AuthenticatedInstructorAssignmentsIdGradebookRoute
  '/student/assignments/$id/checkpoints/$checkpointId': typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/admin/academic-context': typeof AuthenticatedAdminAcademicContextRoute
  '/admin/academic-records': typeof AuthenticatedAdminAcademicRecordsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/email-queue': typeof AuthenticatedAdminEmailQueueRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/instructor/academic-records': typeof AuthenticatedInstructorAcademicRecordsRoute
  '/instructor/analytics': typeof AuthenticatedInstructorAnalyticsRoute
  '/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/instructor/feedback-snippets': typeof AuthenticatedInstructorFeedbackSnippetsRoute
  '/instructor/settings': typeof AuthenticatedInstructorSettingsRoute
  '/student/academic-records': typeof AuthenticatedStudentAcademicRecordsRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/settings': typeof AuthenticatedStudentSettingsRoute
  '/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/reset-password': typeof UnauthenticatedAuthResetPasswordRoute
  '/auth/setup-password': typeof UnauthenticatedAuthSetupPasswordRoute
  '/auth/verify-2fa': typeof UnauthenticatedAuthVerify2faRoute
  '/auth/verify-backup-code': typeof UnauthenticatedAuthVerifyBackupCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/calendar/ics': typeof ApiCalendarIcsRoute
  '/admin/templates/$templateId': typeof AuthenticatedAdminTemplatesTemplateIdRoute
  '/admin/templates/import': typeof AuthenticatedAdminTemplatesImportRoute
  '/admin/users/import': typeof AuthenticatedAdminUsersImportRoute
  '/instructor/assignments/$id': typeof AuthenticatedInstructorAssignmentsIdRouteWithChildren
  '/instructor/assignments/new': typeof AuthenticatedInstructorAssignmentsNewRoute
  '/instructor/reviews/$submissionId': typeof AuthenticatedInstructorReviewsSubmissionIdRoute
  '/student/assignments/$id': typeof AuthenticatedStudentAssignmentsIdRouteWithChildren
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/instructor/assignments': typeof AuthenticatedInstructorAssignmentsIndexRoute
  '/instructor/interventions': typeof AuthenticatedInstructorInterventionsIndexRoute
  '/instructor/reviews': typeof AuthenticatedInstructorReviewsIndexRoute
  '/student/assignments': typeof AuthenticatedStudentAssignmentsIndexRoute
  '/instructor/assignments/$id/gradebook': typeof AuthenticatedInstructorAssignmentsIdGradebookRoute
  '/student/assignments/$id/checkpoints/$checkpointId': typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/_authenticated/admin/academic-context': typeof AuthenticatedAdminAcademicContextRoute
  '/_authenticated/admin/academic-records': typeof AuthenticatedAdminAcademicRecordsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/email-queue': typeof AuthenticatedAdminEmailQueueRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/instructor/academic-records': typeof AuthenticatedInstructorAcademicRecordsRoute
  '/_authenticated/instructor/analytics': typeof AuthenticatedInstructorAnalyticsRoute
  '/_authenticated/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/_authenticated/instructor/feedback-snippets': typeof AuthenticatedInstructorFeedbackSnippetsRoute
  '/_authenticated/instructor/settings': typeof AuthenticatedInstructorSettingsRoute
  '/_authenticated/student/academic-records': typeof AuthenticatedStudentAcademicRecordsRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/settings': typeof AuthenticatedStudentSettingsRoute
  '/_unauthenticated/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/_unauthenticated/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/_unauthenticated/auth/reset-password': typeof UnauthenticatedAuthResetPasswordRoute
  '/_unauthenticated/auth/setup-password': typeof UnauthenticatedAuthSetupPasswordRoute
  '/_unauthenticated/auth/verify-2fa': typeof UnauthenticatedAuthVerify2faRoute
  '/_unauthenticated/auth/verify-backup-code': typeof UnauthenticatedAuthVerifyBackupCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/calendar/ics': typeof ApiCalendarIcsRoute
  '/_authenticated/admin/templates/$templateId': typeof AuthenticatedAdminTemplatesTemplateIdRoute
  '/_authenticated/admin/templates/import': typeof AuthenticatedAdminTemplatesImportRoute
  '/_authenticated/admin/users/import': typeof AuthenticatedAdminUsersImportRoute
  '/_authenticated/instructor/assignments/$id': typeof AuthenticatedInstructorAssignmentsIdRouteWithChildren
  '/_authenticated/instructor/assignments/new': typeof AuthenticatedInstructorAssignmentsNewRoute
  '/_authenticated/instructor/reviews/$submissionId': typeof AuthenticatedInstructorReviewsSubmissionIdRoute
  '/_authenticated/student/assignments/$id': typeof AuthenticatedStudentAssignmentsIdRouteWithChildren
  '/_authenticated/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/instructor/assignments/': typeof AuthenticatedInstructorAssignmentsIndexRoute
  '/_authenticated/instructor/interventions/': typeof AuthenticatedInstructorInterventionsIndexRoute
  '/_authenticated/instructor/reviews/': typeof AuthenticatedInstructorReviewsIndexRoute
  '/_authenticated/student/assignments/': typeof AuthenticatedStudentAssignmentsIndexRoute
  '/_authenticated/instructor/assignments/$id/gradebook': typeof AuthenticatedInstructorAssignmentsIdGradebookRoute
  '/_authenticated/student/assignments/$id/checkpoints/$checkpointId': typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/api/health'
    | '/admin/academic-context'
    | '/admin/academic-records'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/dashboard'
    | '/admin/email-queue'
    | '/admin/settings'
    | '/instructor/academic-records'
    | '/instructor/analytics'
    | '/instructor/dashboard'
    | '/instructor/feedback-snippets'
    | '/instructor/settings'
    | '/student/academic-records'
    | '/student/dashboard'
    | '/student/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/auth/verify-2fa'
    | '/auth/verify-backup-code'
    | '/api/auth/$'
    | '/api/calendar/ics'
    | '/admin/templates/$templateId'
    | '/admin/templates/import'
    | '/admin/users/import'
    | '/instructor/assignments/$id'
    | '/instructor/assignments/new'
    | '/instructor/reviews/$submissionId'
    | '/student/assignments/$id'
    | '/admin/templates/'
    | '/admin/users/'
    | '/instructor/assignments/'
    | '/instructor/interventions/'
    | '/instructor/reviews/'
    | '/student/assignments/'
    | '/instructor/assignments/$id/gradebook'
    | '/student/assignments/$id/checkpoints/$checkpointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/api/health'
    | '/admin/academic-context'
    | '/admin/academic-records'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/dashboard'
    | '/admin/email-queue'
    | '/admin/settings'
    | '/instructor/academic-records'
    | '/instructor/analytics'
    | '/instructor/dashboard'
    | '/instructor/feedback-snippets'
    | '/instructor/settings'
    | '/student/academic-records'
    | '/student/dashboard'
    | '/student/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/auth/verify-2fa'
    | '/auth/verify-backup-code'
    | '/api/auth/$'
    | '/api/calendar/ics'
    | '/admin/templates/$templateId'
    | '/admin/templates/import'
    | '/admin/users/import'
    | '/instructor/assignments/$id'
    | '/instructor/assignments/new'
    | '/instructor/reviews/$submissionId'
    | '/student/assignments/$id'
    | '/admin/templates'
    | '/admin/users'
    | '/instructor/assignments'
    | '/instructor/interventions'
    | '/instructor/reviews'
    | '/student/assignments'
    | '/instructor/assignments/$id/gradebook'
    | '/student/assignments/$id/checkpoints/$checkpointId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/admin'
    | '/_authenticated/instructor'
    | '/_authenticated/student'
    | '/api/health'
    | '/_authenticated/admin/academic-context'
    | '/_authenticated/admin/academic-records'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/email-queue'
    | '/_authenticated/admin/settings'
    | '/_authenticated/instructor/academic-records'
    | '/_authenticated/instructor/analytics'
    | '/_authenticated/instructor/dashboard'
    | '/_authenticated/instructor/feedback-snippets'
    | '/_authenticated/instructor/settings'
    | '/_authenticated/student/academic-records'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/settings'
    | '/_unauthenticated/auth/forgot-password'
    | '/_unauthenticated/auth/login'
    | '/_unauthenticated/auth/reset-password'
    | '/_unauthenticated/auth/setup-password'
    | '/_unauthenticated/auth/verify-2fa'
    | '/_unauthenticated/auth/verify-backup-code'
    | '/api/auth/$'
    | '/api/calendar/ics'
    | '/_authenticated/admin/templates/$templateId'
    | '/_authenticated/admin/templates/import'
    | '/_authenticated/admin/users/import'
    | '/_authenticated/instructor/assignments/$id'
    | '/_authenticated/instructor/assignments/new'
    | '/_authenticated/instructor/reviews/$submissionId'
    | '/_authenticated/student/assignments/$id'
    | '/_authenticated/admin/templates/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/instructor/assignments/'
    | '/_authenticated/instructor/interventions/'
    | '/_authenticated/instructor/reviews/'
    | '/_authenticated/student/assignments/'
    | '/_authenticated/instructor/assignments/$id/gradebook'
    | '/_authenticated/student/assignments/$id/checkpoints/$checkpointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCalendarIcsRoute: typeof ApiCalendarIcsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor': {
      id: '/_authenticated/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthenticatedInstructorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/calendar/ics': {
      id: '/api/calendar/ics'
      path: '/api/calendar/ics'
      fullPath: '/api/calendar/ics'
      preLoaderRoute: typeof ApiCalendarIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/auth/verify-backup-code': {
      id: '/_unauthenticated/auth/verify-backup-code'
      path: '/auth/verify-backup-code'
      fullPath: '/auth/verify-backup-code'
      preLoaderRoute: typeof UnauthenticatedAuthVerifyBackupCodeRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/verify-2fa': {
      id: '/_unauthenticated/auth/verify-2fa'
      path: '/auth/verify-2fa'
      fullPath: '/auth/verify-2fa'
      preLoaderRoute: typeof UnauthenticatedAuthVerify2faRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/setup-password': {
      id: '/_unauthenticated/auth/setup-password'
      path: '/auth/setup-password'
      fullPath: '/auth/setup-password'
      preLoaderRoute: typeof UnauthenticatedAuthSetupPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/reset-password': {
      id: '/_unauthenticated/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof UnauthenticatedAuthResetPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/login': {
      id: '/_unauthenticated/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof UnauthenticatedAuthLoginRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/forgot-password': {
      id: '/_unauthenticated/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof UnauthenticatedAuthForgotPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/student/settings': {
      id: '/_authenticated/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof AuthenticatedStudentSettingsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/academic-records': {
      id: '/_authenticated/student/academic-records'
      path: '/academic-records'
      fullPath: '/student/academic-records'
      preLoaderRoute: typeof AuthenticatedStudentAcademicRecordsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/instructor/settings': {
      id: '/_authenticated/instructor/settings'
      path: '/settings'
      fullPath: '/instructor/settings'
      preLoaderRoute: typeof AuthenticatedInstructorSettingsRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/feedback-snippets': {
      id: '/_authenticated/instructor/feedback-snippets'
      path: '/feedback-snippets'
      fullPath: '/instructor/feedback-snippets'
      preLoaderRoute: typeof AuthenticatedInstructorFeedbackSnippetsRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/dashboard': {
      id: '/_authenticated/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof AuthenticatedInstructorDashboardRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/analytics': {
      id: '/_authenticated/instructor/analytics'
      path: '/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof AuthenticatedInstructorAnalyticsRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/academic-records': {
      id: '/_authenticated/instructor/academic-records'
      path: '/academic-records'
      fullPath: '/instructor/academic-records'
      preLoaderRoute: typeof AuthenticatedInstructorAcademicRecordsRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email-queue': {
      id: '/_authenticated/admin/email-queue'
      path: '/email-queue'
      fullPath: '/admin/email-queue'
      preLoaderRoute: typeof AuthenticatedAdminEmailQueueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/academic-records': {
      id: '/_authenticated/admin/academic-records'
      path: '/academic-records'
      fullPath: '/admin/academic-records'
      preLoaderRoute: typeof AuthenticatedAdminAcademicRecordsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/academic-context': {
      id: '/_authenticated/admin/academic-context'
      path: '/academic-context'
      fullPath: '/admin/academic-context'
      preLoaderRoute: typeof AuthenticatedAdminAcademicContextRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/assignments/': {
      id: '/_authenticated/student/assignments/'
      path: '/assignments'
      fullPath: '/student/assignments/'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/instructor/reviews/': {
      id: '/_authenticated/instructor/reviews/'
      path: '/reviews'
      fullPath: '/instructor/reviews/'
      preLoaderRoute: typeof AuthenticatedInstructorReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/interventions/': {
      id: '/_authenticated/instructor/interventions/'
      path: '/interventions'
      fullPath: '/instructor/interventions/'
      preLoaderRoute: typeof AuthenticatedInstructorInterventionsIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/assignments/': {
      id: '/_authenticated/instructor/assignments/'
      path: '/assignments'
      fullPath: '/instructor/assignments/'
      preLoaderRoute: typeof AuthenticatedInstructorAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates/': {
      id: '/_authenticated/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/assignments/$id': {
      id: '/_authenticated/student/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/student/assignments/$id'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/instructor/reviews/$submissionId': {
      id: '/_authenticated/instructor/reviews/$submissionId'
      path: '/reviews/$submissionId'
      fullPath: '/instructor/reviews/$submissionId'
      preLoaderRoute: typeof AuthenticatedInstructorReviewsSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/assignments/new': {
      id: '/_authenticated/instructor/assignments/new'
      path: '/assignments/new'
      fullPath: '/instructor/assignments/new'
      preLoaderRoute: typeof AuthenticatedInstructorAssignmentsNewRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/assignments/$id': {
      id: '/_authenticated/instructor/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/instructor/assignments/$id'
      preLoaderRoute: typeof AuthenticatedInstructorAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/admin/users/import': {
      id: '/_authenticated/admin/users/import'
      path: '/users/import'
      fullPath: '/admin/users/import'
      preLoaderRoute: typeof AuthenticatedAdminUsersImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates/import': {
      id: '/_authenticated/admin/templates/import'
      path: '/templates/import'
      fullPath: '/admin/templates/import'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates/$templateId': {
      id: '/_authenticated/admin/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/admin/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/instructor/assignments/$id/gradebook': {
      id: '/_authenticated/instructor/assignments/$id/gradebook'
      path: '/gradebook'
      fullPath: '/instructor/assignments/$id/gradebook'
      preLoaderRoute: typeof AuthenticatedInstructorAssignmentsIdGradebookRouteImport
      parentRoute: typeof AuthenticatedInstructorAssignmentsIdRoute
    }
    '/_authenticated/student/assignments/$id/checkpoints/$checkpointId': {
      id: '/_authenticated/student/assignments/$id/checkpoints/$checkpointId'
      path: '/checkpoints/$checkpointId'
      fullPath: '/student/assignments/$id/checkpoints/$checkpointId'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRouteImport
      parentRoute: typeof AuthenticatedStudentAssignmentsIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcademicContextRoute: typeof AuthenticatedAdminAcademicContextRoute
  AuthenticatedAdminAcademicRecordsRoute: typeof AuthenticatedAdminAcademicRecordsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEmailQueueRoute: typeof AuthenticatedAdminEmailQueueRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTemplatesTemplateIdRoute: typeof AuthenticatedAdminTemplatesTemplateIdRoute
  AuthenticatedAdminTemplatesImportRoute: typeof AuthenticatedAdminTemplatesImportRoute
  AuthenticatedAdminUsersImportRoute: typeof AuthenticatedAdminUsersImportRoute
  AuthenticatedAdminTemplatesIndexRoute: typeof AuthenticatedAdminTemplatesIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcademicContextRoute:
    AuthenticatedAdminAcademicContextRoute,
  AuthenticatedAdminAcademicRecordsRoute:
    AuthenticatedAdminAcademicRecordsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEmailQueueRoute: AuthenticatedAdminEmailQueueRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTemplatesTemplateIdRoute:
    AuthenticatedAdminTemplatesTemplateIdRoute,
  AuthenticatedAdminTemplatesImportRoute:
    AuthenticatedAdminTemplatesImportRoute,
  AuthenticatedAdminUsersImportRoute: AuthenticatedAdminUsersImportRoute,
  AuthenticatedAdminTemplatesIndexRoute: AuthenticatedAdminTemplatesIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedInstructorAssignmentsIdRouteChildren {
  AuthenticatedInstructorAssignmentsIdGradebookRoute: typeof AuthenticatedInstructorAssignmentsIdGradebookRoute
}

const AuthenticatedInstructorAssignmentsIdRouteChildren: AuthenticatedInstructorAssignmentsIdRouteChildren =
  {
    AuthenticatedInstructorAssignmentsIdGradebookRoute:
      AuthenticatedInstructorAssignmentsIdGradebookRoute,
  }

const AuthenticatedInstructorAssignmentsIdRouteWithChildren =
  AuthenticatedInstructorAssignmentsIdRoute._addFileChildren(
    AuthenticatedInstructorAssignmentsIdRouteChildren,
  )

interface AuthenticatedInstructorRouteChildren {
  AuthenticatedInstructorAcademicRecordsRoute: typeof AuthenticatedInstructorAcademicRecordsRoute
  AuthenticatedInstructorAnalyticsRoute: typeof AuthenticatedInstructorAnalyticsRoute
  AuthenticatedInstructorDashboardRoute: typeof AuthenticatedInstructorDashboardRoute
  AuthenticatedInstructorFeedbackSnippetsRoute: typeof AuthenticatedInstructorFeedbackSnippetsRoute
  AuthenticatedInstructorSettingsRoute: typeof AuthenticatedInstructorSettingsRoute
  AuthenticatedInstructorAssignmentsIdRoute: typeof AuthenticatedInstructorAssignmentsIdRouteWithChildren
  AuthenticatedInstructorAssignmentsNewRoute: typeof AuthenticatedInstructorAssignmentsNewRoute
  AuthenticatedInstructorReviewsSubmissionIdRoute: typeof AuthenticatedInstructorReviewsSubmissionIdRoute
  AuthenticatedInstructorAssignmentsIndexRoute: typeof AuthenticatedInstructorAssignmentsIndexRoute
  AuthenticatedInstructorInterventionsIndexRoute: typeof AuthenticatedInstructorInterventionsIndexRoute
  AuthenticatedInstructorReviewsIndexRoute: typeof AuthenticatedInstructorReviewsIndexRoute
}

const AuthenticatedInstructorRouteChildren: AuthenticatedInstructorRouteChildren =
  {
    AuthenticatedInstructorAcademicRecordsRoute:
      AuthenticatedInstructorAcademicRecordsRoute,
    AuthenticatedInstructorAnalyticsRoute:
      AuthenticatedInstructorAnalyticsRoute,
    AuthenticatedInstructorDashboardRoute:
      AuthenticatedInstructorDashboardRoute,
    AuthenticatedInstructorFeedbackSnippetsRoute:
      AuthenticatedInstructorFeedbackSnippetsRoute,
    AuthenticatedInstructorSettingsRoute: AuthenticatedInstructorSettingsRoute,
    AuthenticatedInstructorAssignmentsIdRoute:
      AuthenticatedInstructorAssignmentsIdRouteWithChildren,
    AuthenticatedInstructorAssignmentsNewRoute:
      AuthenticatedInstructorAssignmentsNewRoute,
    AuthenticatedInstructorReviewsSubmissionIdRoute:
      AuthenticatedInstructorReviewsSubmissionIdRoute,
    AuthenticatedInstructorAssignmentsIndexRoute:
      AuthenticatedInstructorAssignmentsIndexRoute,
    AuthenticatedInstructorInterventionsIndexRoute:
      AuthenticatedInstructorInterventionsIndexRoute,
    AuthenticatedInstructorReviewsIndexRoute:
      AuthenticatedInstructorReviewsIndexRoute,
  }

const AuthenticatedInstructorRouteWithChildren =
  AuthenticatedInstructorRoute._addFileChildren(
    AuthenticatedInstructorRouteChildren,
  )

interface AuthenticatedStudentAssignmentsIdRouteChildren {
  AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute: typeof AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute
}

const AuthenticatedStudentAssignmentsIdRouteChildren: AuthenticatedStudentAssignmentsIdRouteChildren =
  {
    AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute:
      AuthenticatedStudentAssignmentsIdCheckpointsCheckpointIdRoute,
  }

const AuthenticatedStudentAssignmentsIdRouteWithChildren =
  AuthenticatedStudentAssignmentsIdRoute._addFileChildren(
    AuthenticatedStudentAssignmentsIdRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentAcademicRecordsRoute: typeof AuthenticatedStudentAcademicRecordsRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentSettingsRoute: typeof AuthenticatedStudentSettingsRoute
  AuthenticatedStudentAssignmentsIdRoute: typeof AuthenticatedStudentAssignmentsIdRouteWithChildren
  AuthenticatedStudentAssignmentsIndexRoute: typeof AuthenticatedStudentAssignmentsIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentAcademicRecordsRoute:
    AuthenticatedStudentAcademicRecordsRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentSettingsRoute: AuthenticatedStudentSettingsRoute,
  AuthenticatedStudentAssignmentsIdRoute:
    AuthenticatedStudentAssignmentsIdRouteWithChildren,
  AuthenticatedStudentAssignmentsIndexRoute:
    AuthenticatedStudentAssignmentsIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInstructorRoute: typeof AuthenticatedInstructorRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInstructorRoute: AuthenticatedInstructorRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedAuthForgotPasswordRoute: typeof UnauthenticatedAuthForgotPasswordRoute
  UnauthenticatedAuthLoginRoute: typeof UnauthenticatedAuthLoginRoute
  UnauthenticatedAuthResetPasswordRoute: typeof UnauthenticatedAuthResetPasswordRoute
  UnauthenticatedAuthSetupPasswordRoute: typeof UnauthenticatedAuthSetupPasswordRoute
  UnauthenticatedAuthVerify2faRoute: typeof UnauthenticatedAuthVerify2faRoute
  UnauthenticatedAuthVerifyBackupCodeRoute: typeof UnauthenticatedAuthVerifyBackupCodeRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedAuthForgotPasswordRoute:
    UnauthenticatedAuthForgotPasswordRoute,
  UnauthenticatedAuthLoginRoute: UnauthenticatedAuthLoginRoute,
  UnauthenticatedAuthResetPasswordRoute: UnauthenticatedAuthResetPasswordRoute,
  UnauthenticatedAuthSetupPasswordRoute: UnauthenticatedAuthSetupPasswordRoute,
  UnauthenticatedAuthVerify2faRoute: UnauthenticatedAuthVerify2faRoute,
  UnauthenticatedAuthVerifyBackupCodeRoute:
    UnauthenticatedAuthVerifyBackupCodeRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCalendarIcsRoute: ApiCalendarIcsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
